remote_theme: pages-themes/cayman@v0.2.0
title: Bjergsted Blåseensemble
description: Velkommen!
github:
  is_project_page: false
  show_downloads: false
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
